### ISSUE TITLE
various config errors for Sndfile and Qt5

### ISSUE THREAD

**Issue by NHQ** [marsyas/marsyas#55] opened 2016-01-11 20:05 UTC
I have qt5 and sendfile installed, not sure how to address these config errors.

```
  By not providing "FindSndfile.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Sndfile", but
  CMake did not find one.

  Could not find a package configuration file provided by "Sndfile" with any
  of the following names:

    SndfileConfig.cmake
    sndfile-config.cmake

  Add the installation prefix of "Sndfile" to CMAKE_PREFIX_PATH or set
  "Sndfile_DIR" to a directory containing one of the above files.  If
  "Sndfile" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:47 (include)


CMake Warning at cmake-modules/marsyas-detect.cmake:105 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core"
  (requested version 5.1) with any of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:47 (include)


CMake Error at cmake-modules/marsyas-detect.cmake:114 (message):
  Could not find a suitable version of Qt 5 (>= 5.1).

  If you have installed Qt 5 in a non-standard location, please add the Qt
  directory that contains subdirectories 'bin' and 'lib' to the CMake
  variable CMAKE_PREFIX_PATH.

  You can also disable building Qt5 applications by setting the CMake
  variable WITH_QT to OFF.

Call Stack (most recent call first):
  src/CMakeLists.txt:47 (include)
```

**Comment by jleben** [comment] 2016-01-12 17:44
There was an issue with finding libsndfile which has been just fixed on the master branch.

The Qt error is not a bug: please follow the instructions in the message you posted above, and add the Qt5 directory to the CMAKE_PREFIX_PATH variable. Or build without Qt5 as instructed in that message.

Libsndfile is optional. If you want to use the "LibsndfileSource" Marsystem, then you need to also add the location of your libsndfile library to the CMAKE_PREFIX_PATH variable (in the same ways as for Qt5).

**Closed by jleben** 2016-01-12 17:44 UTC

**Comment by NHQ** [comment] 2016-01-12 18:54
Thank you, but CMAKE_PREFIX_PATH is not explicit, and neither is the instruction for building without Qt5, which I attempted to do but throwing random cmake policies and declaration into various CMakeList.txt, without success.

**Comment by jleben** [comment] 2016-01-12 19:01
What do you mean by "explicit"?

**Comment by NHQ** [comment] 2016-01-12 19:04
I don't know what it means to add anything to it, because I don't know to what it refers or where it is.  Similarly for building without those options, I don't know what to tell cmake or where to tell it.

**Comment by jleben** [comment] 2016-01-12 19:06
For building Marsyas succefully, I suggest to please read the CMake manual (just the basics).

Otherwise, perhaps the pre-built Marsyas downloads would work for you:
http://marsyas.info/downloads/binaries.html

**Comment by NHQ** [comment] 2016-01-12 20:01
No linux binaries :\

I'll read up on cmake...
